[package]
name = "freedit"
version = "0.2.10"
edition = "2021"
license = "MIT"

[dependencies]
askama = { version = "0.11", default-features = false } # templates engine 
atom_syndication = { version = "0.12.0", default-features = false }
axum = { version = "0.6.4", features = ["http2", "headers", "form", "query", "multipart", "tokio"], default-features = false }
axum-server = { version = "0.4", features = ["tls-rustls"] }
bincode = "2.0.0-rc.2"
captcha = { version = "0.0.9", default-features = false }
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
data-encoding = "*"
identicon = { git = "https://github.com/freedit-dev/identicon.git", default-features = false }
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "gif"] }
img-parts = "0.3.0"
indexmap = "1.9.2"
latex2mathml = "0.2.3"
mozjpeg = "0.9.4"
nanoid = "0.4.0"
once_cell = "*"
pulldown-cmark = { version = "0.9", features = ["simd"], default-features = false }
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
ring = { version = "0.16.20", default-features = false }
rss = { version = "2.0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
sled = { version = "0.34.7", features = ["compression"] }
syntect = { version = "5", features = ["regex-fancy", "default-syntaxes", "default-themes", "html"], default-features = false }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
toml = "0.7.1"
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.3", features = ["fs", "compression-gzip", "trace"] } # serve dir
tracing = { version = "0.1", features = ["release_max_level_info", "max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.16", features = ["derive"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
