[package]
name = "freedit"
version = "0.1.0-rc.1"
edition = "2021"
license = "MIT"

[dependencies]
askama = { version = "0.11", default-features = false } # templates engine 
axum = { version = "0.6.0-rc.1", features = ["http2", "headers", "form", "query", "multipart"], default-features = false }
axum-server = { version = "0.4", features = ["tls-rustls"] }
bincode = "2.0.0-rc.1"
captcha = { version = "0.0.9", default-features = false }
data-encoding = "*"
flate2 = "1.0"
hash_avatar = { git = "https://github.com/t924417424/rust_hash_avatar" }
http-body = "0.4.5"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "gif"] }
latex2mathml = "0.2.3"
nanoid = "0.4.0"
once_cell = "*"
pulldown-cmark = { version = "0.9", features = ["simd"], default-features = false }
ring = { version = "0.16.20", default-features = false }
serde = { version = "1.0", features = ["derive"] }
sled = { version = "0.34.7", features = ["compression"] }
syntect = { version = "5", features = ["regex-fancy", "default-syntaxes", "default-themes", "html"], default-features = false }
thiserror = "1"
time = { version = "0.3", features = ["std"], default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
toml = "0.5"
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.3", features = ["fs", "compression-gzip", "trace"] } # serve dir
tracing = { version = "0.1", features = ["release_max_level_info", "max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
